# Generated by Django 2.2.4 on 2019-09-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pofile',
            name='profile_pic',
            field=models.ImageField(default='profile.png', upload_to='profile_pics/'),
        ),
    ]
