# Generated by Django 2.2.4 on 2019-09-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pofile',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
