# Generated by Django 2.2.4 on 2019-09-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pofile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pofile',
            name='fullname',
        ),
    ]
